"""Initial migration

Revision ID: 66ea6352b04e
Revises: 
Create Date: 2025-02-01 12:11:36.656133

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66ea6352b04e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice',
    sa.Column('voice_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('detetime_sent', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('voice_id')
    )
    op.create_table('analyzedvoice',
    sa.Column('voice_id', sa.Uuid(), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=False),
    sa.Column('average_entropy', sa.Float(), nullable=True),
    sa.Column('overlapping_entropy', sa.Float(), nullable=True),
    sa.Column('predicted_label', sa.Boolean(), nullable=False),
    sa.Column('actual_label', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['voice_id'], ['voice.voice_id'], ),
    sa.PrimaryKeyConstraint('voice_id')
    )
    op.drop_table('celery_taskmeta')
    op.drop_table('celery_tasksetmeta')

    op.execute(
        """CREATE VIEW voiceverbose AS
        SELECT 
            voice.voice_id,
            voice.embedding,
            voice.detetime_sent,
            voice.sender_id,
            analyzedvoice.entropy,
            analyzedvoice.average_entropy,
            analyzedvoice.overlapping_entropy,
            analyzedvoice.predicted_label,
            analyzedvoice.actual_label
        FROM voice JOIN analyzedvoice ON voice.voice_id = analyzedvoice.voice_id;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_tasksetmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='celery_tasksetmeta_pkey'),
    sa.UniqueConstraint('taskset_id', name='celery_tasksetmeta_taskset_id_key')
    )
    op.create_table('celery_taskmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('kwargs', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('worker', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='celery_taskmeta_pkey'),
    sa.UniqueConstraint('task_id', name='celery_taskmeta_task_id_key')
    )
    op.execute("DROP VIEW voiceverbose;")
    op.drop_table('analyzedvoice')
    op.drop_table('voice')
    # ### end Alembic commands ###
