"""Initial migration

Revision ID: ea42b778c5c9
Revises: 
Create Date: 2025-02-07 23:18:39.343356

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea42b778c5c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice',
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('detetime_sent', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preprocessed', sa.Boolean(), nullable=False, default=False),
    sa.PrimaryKeyConstraint('voice_id')
    )
    op.create_table('analyzedvoice',
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=False),
    sa.Column('average_entropy', sa.Float(), nullable=True),
    sa.Column('overlapping_entropy', sa.Float(), nullable=True),
    sa.Column('predicted_label', sa.Boolean(), nullable=False),
    sa.Column('actual_label', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['voice_id'], ['voice.voice_id'], ),
    sa.PrimaryKeyConstraint('voice_id')
    )
    op.execute(
        """CREATE VIEW voiceverbose AS
        SELECT 
            voice.voice_id,
            voice.embedding,
            voice.detetime_sent,
            voice.sender_id,
            analyzedvoice.entropy,
            analyzedvoice.average_entropy,
            analyzedvoice.overlapping_entropy,
            analyzedvoice.predicted_label,
            analyzedvoice.actual_label
        FROM voice JOIN analyzedvoice ON voice.voice_id = analyzedvoice.voice_id;
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW voiceverbose;")
    op.drop_table('analyzedvoice')
    op.drop_table('voice')
    # ### end Alembic commands ###
